[template]
name = "my-template"
description = "My custom template for Rust projects"
authors = ["Medov Timur"]
version = "0.1.0"

[placeholders.project-name-snake-case]
type = "string"
prompt = "Project name (snake_case)"
regex = "^[a-z][a-z0-9_]*$"
default = "{{ project-name | snake_case }}"
